---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86131.
--- DateTime: 2025/10/30 13:46
---
-- 用于异步秒杀

local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

-- stockKey的值为string类型
-- orderKey的值为sei类型
local stockKey = "seckill:stock:" .. voucherId
local orderKey = "seckill:order:" .. voucherId

if(tonumber(redis.call('get',stockKey)) < 1) then
    -- 库存不足，返回1
    return 1
end
if(redis.call('sismember',orderKey,userId) == 1) then
    -- 用户在set集合中已经存在，说明重复下单，返回2
    return 2
end
-- 校验通过，删减库存，添加用户id到集合中。返回0
redis.call("incrby",stockKey,-1)
redis.call("sadd",orderKey,userId)

redis.call('xadd','stream.orders"','*','id',orderId,'userId',userId,'voucherId',voucherId)

return 0